apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "presto-coordinator-config"
data:
  clp.properties: |
    connector.name=clp
    clp.metadata-provider-type=mysql
    clp.metadata-db-url=jdbc:mysql://${REPLACE_ME}:6001
    clp.metadata-db-name=clp-db
    clp.metadata-db-user=${REPLACE_ME}
    clp.metadata-db-password=${REPLACE_ME}
    clp.metadata-table-prefix=clp_
    clp.split-provider-type=mysql
    clp.metadata-filter-config=/opt/presto-server/etc/metadata-filter.json

  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=1GB
    query.max-memory-per-node=1GB
    discovery-server.enabled=true
    discovery.uri=http://{{ .Values.presto.coordinator.serviceName }}:{{ .Values.presto.coordinator.httpPort }}
    optimizer.optimize-hash-generation=false
    regex-library=RE2J
    use-alternative-function-signatures=true
    inline-sql-functions=false
    nested-data-serialization-enabled=false
    native-execution-enabled=true

  jvm.config: |
    -server
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    -Xmx4G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true

  log.properties: |
    com.facebook.presto=DEBUG

  metadata-filter.json: |
    {
    }

  node.properties: |
    node.environment=production
    node.id={{ .Values.presto.coordinator.serviceName }}
