name: YScope Presto - CLP Connector Stable Release - Publish

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'Release version (e.g., 0.292)'
        required: true
      publish_release_tag:
        description: 'Publish release tag'
        type: boolean
        default: true
        required: false
      publish_maven:
        description: 'Publish maven artifacts'
        type: boolean
        default: true
        required: false
      publish_github_release:
        description: 'Publish executable jars to github release'
        type: boolean
        default: true
        required: false
      publish_image:
        description: 'Publish presto docker image'
        type: boolean
        default: true
        required: false
      publish_native_image:
        description: 'Publish prestissimo docker image'
        type: boolean
        default: true
        required: false
      publish_docs:
        description: 'Publish docs'
        type: boolean
        default: true
        required: false

env:
  JAVA_VERSION: ${{ vars.JAVA_VERSION || '17' }}
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION || 'temurin' }}
  MAVEN_OPTS: ${{ vars.MAVEN_OPTS }}
  DOCKER_REPO: ${{ github.repository }}
  ORG_NAME: ${{ github.repository_owner }}
  IMAGE_NAME: presto-native
  RELEASE_BRANCH: release-${{ inputs.RELEASE_VERSION }}
  RELEASE_TAG: ${{ inputs.RELEASE_VERSION }}
  GIT_CI_USER: ${{ github.actor }}
  GIT_CI_EMAIL: "${{ github.actor }}@users.noreply.github.com"
  MAVEN_AUTO_PUBLISH: ${{ vars.MAVEN_AUTO_PUBLISH || 'true' }}

jobs:
  publish-release-tag:
    if: github.event.inputs.publish_release_tag == 'true'
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
          show-progress: false

      - name: Configure Git
        run: |
          git config --global user.email "${{ env.GIT_CI_EMAIL }}"
          git config --global user.name "${{ env.GIT_CI_USER }}"
          git config pull.rebase false

      - name: Delete existing release tag
        run: |
          git push --delete origin ${{ env.RELEASE_TAG }} || true
          git tag -d ${{ env.RELEASE_TAG }} || true

      - name: Create new release tag
        run: |
          git tag -a ${{ env.RELEASE_TAG }} -m "release ${{ env.RELEASE_TAG }}"
          git push origin ${{ env.RELEASE_BRANCH }} --tags

  publish-maven-artifacts:
    needs: publish-release-tag
    if: |
      (!failure() &&!cancelled()) && (
        github.event.inputs.publish_maven == 'true' ||
        github.event.inputs.publish_image == 'true' ||
        github.event.inputs.publish_docs == 'true' ||
        github.event.inputs.publish_github_release == 'true'
      )
    runs-on: ubuntu-latest
    environment: release
    timeout-minutes: 60

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Set up JDK ${{ env.JAVA_DISTRIBUTION }}/${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          overwrite-settings: true

      - name: Install dependencies
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y build-essential git gpg python3 python3-venv

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git
        run: |
          git config --global user.email "${{ env.GIT_CI_EMAIL }}"
          git config --global user.name "${{ env.GIT_CI_USER }}"
          git config pull.rebase false

      - name: Build release artifacts
        run: ./mvnw clean install -DskipTests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: presto-artifacts-${{ env.RELEASE_TAG }}
          retention-days: 7
          path: |
            presto-server/target/presto-server-*.tar.gz
            presto-docs/target/presto-docs-*.zip
            presto-cli/target/presto-cli-*-executable.jar
            presto-benchmark-driver/target/presto-benchmark-driver-*-executable.jar
            presto-testing-server-launcher/target/presto-testing-server-launcher-*-executable.jar

  publish-github-release:
    needs: publish-maven-artifacts
    if: (!failure() && !cancelled()) && github.event.inputs.publish_github_release == 'true'
    runs-on: ubuntu-latest
    environment: release
    timeout-minutes: 150
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_TAG}}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: presto-artifacts-${{ env.RELEASE_TAG }}
          path: ./

      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: YScope Presto - CLP Connector ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Release tag: ${{ env.RELEASE_TAG }}
          files: |
            ./presto-cli/target/presto-cli-*-executable.jar
            ./presto-benchmark-driver/target/presto-benchmark-driver-*-executable.jar
            ./presto-testing-server-launcher/target/presto-testing-server-launcher-*-executable.jar

  publish-docker-image:
    needs: publish-maven-artifacts
    if: (!failure() && !cancelled()) && github.event.inputs.publish_image == 'true'
    runs-on: ubuntu-latest
    environment: release
    timeout-minutes: 150
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_TAG}}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: presto-artifacts-${{ env.RELEASE_TAG }}
          path: ./

      - name: "Login to image registry"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{github.actor}}"
          password: "${{secrets.GITHUB_TOKEN}}"

      - name: Move artifacts to docker directory
        run: |
          mv ./presto-server/target/presto-server-*.tar.gz docker/
          mv ./presto-cli/target/presto-cli-*-executable.jar docker/

      - name: "Set up container image metadata"
        id: "meta"
        uses: "docker/metadata-action@v5"
        with:
          images: "ghcr.io/${{github.repository}}/coordinator"
          tags: "type=raw,value=${{ env.RELEASE_TAG }}"

      - name: Build docker image and publish
        uses: "docker/build-push-action@v6"
        with:
          build-args: |-
            JMX_PROMETHEUS_JAVA_AGENT_VERSION=0.20.0
            PRESTO_VERSION=${{ env.RELEASE_TAG }}
          context: "./docker"
          file: "./docker/Dockerfile"
          push: >-
            ${{ github.ref == format('refs/heads/{0}', env.RELEASE_BRANCH) }}
          tags: "${{steps.meta.outputs.tags}}"
          labels: "${{steps.meta.outputs.labels}}"

  publish-native-image:
    needs: publish-release-tag
    if: (!failure() && !cancelled()) && github.event.inputs.publish_native_image == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    environment: release
    timeout-minutes: 300
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_TAG }}
          submodules: true

      - name: Initialize Prestissimo submodules
        run: |
          df -h
          cd presto-native-execution && make submodules
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: "Login to image registry"
        uses: "docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772"
        with:
          registry: "ghcr.io"
          username: "${{github.actor}}"
          password: "${{secrets.GITHUB_TOKEN}}"

      - name: "Set up metadata for dependency image"
        id: "metadata-deps-image"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        with:
          images: "ghcr.io/${{github.repository}}/prestissimo-worker-dev-env"
          tags: "type=raw,value=${{ env.RELEASE_TAG }}"

      - name: "Build and push dependency image"
        uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
        with:
          context: "./presto-native-execution"
          file: "./presto-native-execution/scripts/dockerfiles/ubuntu-22.04-dependency.dockerfile"
          push: >-
            ${{ github.ref == format('refs/heads/{0}', env.RELEASE_BRANCH) }}
          tags: "${{steps.metadata-deps-image.outputs.tags}}"
          labels: "${{steps.metadata-deps-image.outputs.labels}}"

      - name: "Set up metadata for runtime image"
        id: "metadata-runtime-image"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        with:
          images: "ghcr.io/${{github.repository}}/prestissimo-worker"
          tags: "type=raw,value=${{ env.RELEASE_TAG }}"

      - name: "Get number of cores"
        id: "get-cores"
        run: |-
          echo "num_cores=$(nproc)" >> $GITHUB_OUTPUT

      - name: "Build and push runtime image"
        uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
        with:
          build-args: |-
            BASE_IMAGE=ubuntu:22.04
            DEPENDENCY_IMAGE=${{steps.metadata-deps-image.outputs.tags}}
            EXTRA_CMAKE_FLAGS=-DPRESTO_ENABLE_TESTING=OFF \
              -DPRESTO_ENABLE_PARQUET=ON \
              -DPRESTO_ENABLE_S3=ON
            NUM_THREADS=${{steps.get-cores.outputs.num_cores}}
            OSNAME=ubuntu
          context: "./presto-native-execution"
          file: "./presto-native-execution/scripts/dockerfiles/prestissimo-runtime.dockerfile"
          push: >-
            ${{ github.ref == format('refs/heads/{0}', env.RELEASE_BRANCH) }}
          tags: "${{steps.metadata-runtime-image.outputs.tags}}"
          labels: "${{steps.metadata-runtime-image.outputs.labels}}"
