name: prestocpp-linux-build-and-unit-test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'presto-native-execution/**'
      - 'presto-native-sidecar-plugin/**'
      - '.github/workflows/prestocpp-linux-build-and-unit-test.yml'
  push:
    paths-ignore:
      - 'presto-docs/**'

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency. Exclude the `release-0.297-edge-10-clp-connector` branch so
  # that each commit to release-0.297-edge-10-clp-connector is checked completely.
  cancel-in-progress: "${{github.ref != 'refs/heads/release-0.297-edge-10-clp-connector'}}"

jobs:
  prestocpp-linux-build-for-test:
    runs-on: ubuntu-22.04
    container:
      image: prestodb/presto-native-dependency:0.297-202512180933-75d7d4ea
    env:
      CCACHE_DIR: "${{ github.workspace }}/ccache"
    steps:
      - uses: actions/checkout@v4

      - name: Fix git permissions
        # Usually actions/checkout does this but as we run in a container
        # it doesn't work
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Update velox
        run: |
          cd presto-native-execution
          make velox-submodule

      - name: Install Github CLI for using apache/infrastructure-actions/stash
        run: |
          curl -L https://github.com/cli/cli/releases/download/v2.63.2/gh_2.63.2_linux_amd64.rpm > gh_2.63.2_linux_amd64.rpm
          rpm -iv gh_2.63.2_linux_amd64.rpm

      - uses: apache/infrastructure-actions/stash/restore@4ab8682fbd4623d2b4fc1c98db38aba5091924c3
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-prestocpp-linux-build-for-test

      - name: Zero ccache statistics
        run: ccache -sz

      - name: Build engine
        run: |
          source /opt/rh/gcc-toolset-12/enable
          cd presto-native-execution
          cmake \
            -B _build/release \
            -GNinja \
            -DTREAT_WARNINGS_AS_ERRORS=1 \
            -DENABLE_ALL_WARNINGS=1 \
            -DCMAKE_BUILD_TYPE=Release \
            -DPRESTO_ENABLE_PARQUET=ON \
            -DPRESTO_ENABLE_JWT=ON \
            -DPRESTO_STATS_REPORTER_TYPE=PROMETHEUS \
            -DPRESTO_MEMORY_CHECKER_TYPE=LINUX_MEMORY_CHECKER \
            -DCMAKE_PREFIX_PATH=/usr/local \
            -DThrift_ROOT=/usr/local \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DMAX_LINK_JOBS=4
          ninja -C _build/release -j $(getconf _NPROCESSORS_ONLN)

      - name: Ccache after
        run: ccache -s

      - uses: apache/infrastructure-actions/stash/save@4ab8682fbd4623d2b4fc1c98db38aba5091924c3
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-prestocpp-linux-build-for-test

      - name: Run Unit Tests
        run: |
          # Ensure transitive dependency libboost-iostreams is found.
          ldconfig /usr/local/lib
          cd presto-native-execution/_build/release
          ctest -j $(getconf _NPROCESSORS_ONLN) -VV --output-on-failure --exclude-regex velox.*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: presto-native-build
          path: |
            presto-native-execution/_build/release/presto_cpp/main/presto_server
            presto-native-execution/_build/release/velox/velox/functions/remote/server/velox_functions_remote_server_main



