name: prestocpp-format-and-header-check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'presto-native-execution/**'
      - '.github/workflows/prestocpp-format-and-header-check.yml'
  push:
    paths:
      - 'presto-native-execution/**'
      - '.github/workflows/prestocpp-format-and-header-check.yml'

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency. Exclude the `main` branch so that each commit to main is
  # checked completely.
  cancel-in-progress: "${{github.ref != 'refs/heads/main'}}"

jobs:
  prestocpp-format-and-header-check:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/oss-presto/velox-dev:check
    steps:
      - uses: actions/checkout@v4

      - name: Fix git permissions
        # Usually actions/checkout does this but as we run in a container
        # it doesn't work
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Check formatting
        run: |
          git fetch origin master
          cd presto-native-execution
          make format-check

      - name: Check license headers
        run: |
          git fetch origin master
          cd presto-native-execution
          make header-check
