name: prestissimo-worker-images-build

on:
  pull_request:
  push:

jobs:
  prestissimo-worker-images-build:
    name: prestissimo-worker-images-build
    runs-on: ubuntu-22.04
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Login to image registry"
        uses: "docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772"
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Set up metadata for dependency image"
        id: "metadata-deps-image"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        with:
          images: >-
            ghcr.io/${{github.repository}}/prestissimo-worker-dev-env
          tags: |-
            type=raw,value=dev

      - name: "Build and push dependency image"
        uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
        with:
          context: "./presto-native-execution/"
          file: "./presto-native-execution/scripts/dockerfiles/ubuntu-22.04-dependency.dockerfile"
          push: >-
            ${{github.event_name != 'pull_request'
            && github.ref == 'refs/heads/release-0.293-clp-connector'}}
          tags: "${{steps.metadata-deps-image.outputs.tags}}"
          labels: "${{steps.metadata-deps-image.outputs.labels}}"

      - name: "Set up metadata for runtime image"
        id: "metadata-runtime-image"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        with:
          images: >-
            ghcr.io/${{github.repository}}/prestissimo-worker
          tags: |-
            type=raw,value=dev

      - name: Get number of cores
        id: get-cores
        run: |-
          echo "num_cores=$(nproc)" >> $GITHUB_OUTPUT

      - name: "Build and push runtime image"
        uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
        with:
          build-args: |-
            BASE_IMAGE=ubuntu:22.04
            DEPENDENCY_IMAGE=${{steps.metadata-deps-image.outputs.tags}}
            EXTRA_CMAKE_FLAGS=-DPRESTO_ENABLE_TESTING=OFF -DPRESTO_ENABLE_PARQUET=ON -DPRESTO_ENABLE_S3=ON
            NUM_THREADS=${{steps.get-cores.outputs.num_cores}}
            OSNAME=ubuntu
          context: "./presto-native-execution/"
          file: "./presto-native-execution/scripts/dockerfiles/prestissimo-runtime.dockerfile"
          push: >-
            ${{github.event_name != 'pull_request'
            && github.ref == 'refs/heads/release-0.293-clp-connector'}}
          tags: "${{steps.metadata-runtime-image.outputs.tags}}"
          labels: "${{steps.metadata-runtime-image.outputs.labels}}"
